# https://github.com/vaibhavvikas/jekyll-theme-minimalistic

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-remote-theme

title: PCA4CD
description: PCA4CD is a QGIS plugin that computes Principal Component Analysis (PCA) and can create a change detection layer using PCA's dimensionality reduction properties.
logo: ./img/pca4cd.svg
email:
favicon: true
color-scheme: auto
